app/urls.py
from django.urls import path, include
from django.contrib.auth import views as aut_views
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login_register', views.register_view, name='register'),
    path('index', views.index, name='index'),
    path('libro/<str:olid>/', views.detalle_libro, name='detalle_libro'),
    path('libro/<str:olid>/comentar/', views.add_comment, name='add_comment'),
    path('libro/<str:olid>/rating/', views.update_rating, name='update_rating'),    
    path('mis-libros/', views.mis_libros, name='mis_libros'),
    path('logout/', views.logout_view, name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('login/google/', aut_views.LoginView.as_view(), name='google-login'),
    path('foto/', views.foto_view, name='foto'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('geners/', views.geners, name='geners'),
    path('writers/', views.writers, name='writers')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

bookland/urls.py
# bookland/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Prefer not to say'),
    ]
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)    
    biography = models.TextField(blank=True, null=True)
    registration_date = models.DateTimeField(auto_now_add=True)
    gender = models.CharField(max_length=10, choices=gender_choices)
    favorite_genres = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.username



class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    birth_date = models.DateField(null=True, blank=True)  # Fecha de nacimiento
    country = models.CharField(max_length=100, null=True, blank=True)  # País
    #reaction = models.BooleanField()

    def __str__(self):
        return self.name

class Book(models.Model):
    olid = models.CharField(max_length=50, unique=True)  # Campo para el identificador de Open Library
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

    
class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.book.title}'

class Rating(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='ratings')
    like = models.BooleanField(default=False)
    dislike = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Rating by {self.user.username} for {self.book.title}'

templates/detalle_libro.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Detalles de libro
{% endblock %}

{% block main %}
<link rel="stylesheet" href="{% static 'css/styles_libro.css' %}">

<main>
    <section id="book-description">
        <img src="{{ cover_url }}" alt="{{ libro.title }}" id="libro-photo">
        <h1>{{ libro.title }}</h1>
        <p id="book-summary">{{ libro.description }}</p>
        <div class="like-dislike">
            <i class="bx bxs-like {% if user_rating and user_rating.like %}active{% endif %}" id="like-button"></i>
            <span class="like-count" id="like-count">{{ like_count }}</span>
            <i class="bx bxs-dislike {% if user_rating and user_rating.dislike %}active{% endif %}" id="dislike-button"></i>
            <span class="dislike-count" id="dislike-count">{{ dislike_count }}</span>
        </div>
    </section>
    <hr>
    <h3>Ediciones Disponibles</h3>
    <ul>
        {% for edicion in ediciones_lectura %}
            <li>
                <a href="{{ edicion.url }}">{{ edicion.title }}</a>
                {% if edicion.cover_url %}
                    <img src="{{ edicion.cover_url }}" alt="Portada de la edición">
                {% endif %}
            </li>
        {% empty %}
            <li>No hay ediciones disponibles para leer.</li>
        {% endfor %}
    </ul>
    <hr>
    <section id="comments-section">
        <h3>Comentarios</h3>
        <div id="comments">
            {% for comment in comments %}
            <div class="comment">
                <p><strong>{{ comment.user.username }}</strong>: {{ comment.text }}</p>
                <p class="comment-time">{{ comment.created_at }}</p>
            </div>
            {% endfor %}
        </div>
        <form id="comment-form" action="{% url 'add_comment' olid=olid %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <textarea id="new-comment" name="text" placeholder="Escribe tu comentario aquí..." required></textarea>
            <button type="submit">Enviar</button>
        </form>

        <form id="rating-form" action="{% url 'update_rating' olid=olid %}" method="post" style="display: none;">
            {% csrf_token %}
            <input type="hidden" name="like" id="like-input">
            <input type="hidden" name="dislike" id="dislike-input">
        </form>
    </section>
</main>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const likeButton = document.getElementById('like-button');
    const dislikeButton = document.getElementById('dislike-button');
    const likeCount = document.getElementById('like-count');
    const dislikeCount = document.getElementById('dislike-count');
    const commentForm = document.getElementById('comment-form');
    const newComment = document.getElementById('new-comment');
    const ratingForm = document.getElementById('rating-form');
    const likeInput = document.getElementById('like-input');
    const dislikeInput = document.getElementById('dislike-input');
    const commentsSection = document.getElementById('comments');

    if (!likeButton || !dislikeButton || !likeCount || !dislikeCount || !commentForm || !newComment || !ratingForm || !likeInput || !dislikeInput || !commentsSection) {
        console.error('Error: No se pudieron encontrar uno o más elementos necesarios.');
        return;
    }

    likeButton.addEventListener('click', async () => {
        const isActive = likeButton.classList.contains('active');
        likeInput.value = !isActive;
        dislikeInput.value = false;

        try {
            const response = await updateRating();
            if (response.ok) {
                const data = await response.json();
                updateUI(data);
                if (isActive) {
                    likeButton.classList.remove('active');
                } else {
                    likeButton.classList.add('active');
                    dislikeButton.classList.remove('active');
                }
            } else {
                throw new Error('Error al actualizar el rating.');
            }
        } catch (error) {
            console.error('Error:', error);
        }
    });

    dislikeButton.addEventListener('click', async () => {
        const isActive = dislikeButton.classList.contains('active');
        likeInput.value = false;
        dislikeInput.value = !isActive;

        try {
            const response = await updateRating();
            if (response.ok) {
                const data = await response.json();
                updateUI(data);
                if (isActive) {
                    dislikeButton.classList.remove('active');
                } else {
                    dislikeButton.classList.add('active');
                    likeButton.classList.remove('active');
                }
            } else {
                throw new Error('Error al actualizar el rating.');
            }
        } catch (error) {
            console.error('Error:', error);
        }
    });

    commentForm.addEventListener('submit', async (event) => {
        event.preventDefault();
        const commentText = newComment.value.trim();
        if (commentText) {
            try {
                const response = await fetch(commentForm.action, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': getCookie('csrftoken'),
                    },
                    body: new URLSearchParams(new FormData(commentForm)),
                });

                if (!response.ok) {
                    throw new Error('Error al enviar el comentario.');
                }

                const comment = await response.json();

                // Crear un nuevo elemento de comentario y agregarlo a la lista de comentarios
                const commentElement = document.createElement('div');
                commentElement.className = 'comment';
                commentElement.innerHTML = `
                    <p><strong>${comment.user.username}</strong>: ${comment.text}</p>
                    <p class="comment-time">${comment.created_at}</p>
                `;
                commentsSection.appendChild(commentElement);
                newComment.value = '';
            } catch (error) {
                console.error('Error:', error);
            }
        }
    });

    function updateRating() {
        const formData = new URLSearchParams(new FormData(ratingForm));
        return fetch(ratingForm.action, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-CSRFToken': getCookie('csrftoken'),
            },
            body: formData,
        });
    }

    function updateUI(data) {
        likeCount.textContent = data.like_count;
        dislikeCount.textContent = data.dislike_count;
    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.startsWith(name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
});

</script>
{% endblock %}

templates/escritores.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Escritores
{% endblock %}

{% block main %}
<main>
    <section class="writers-section">
        <h2>Escritores</h2>
        <div class="writers-list">
            {% if authors %}
                {% for author in authors %}
                <div class="writer-card {% if forloop.counter0|divisibleby:2 %}left{% else %}right{% endif %}">
                    <img src="{{ author.image_url }}" alt="{{ author.name }}">
                    <div class="writer-info">
                        <h3>{{ author.name }}</h3>
                        <p>{{ author.description }}</p>
                        <div class="like-dislike">
                            <i class='bx bxs-like'></i> <span class="like-count">0</span>
                            <i class='bx bxs-dislike'></i> <span class="dislike-count">0</span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>No se encontraron autores. Intente buscar de nuevo.</p>
            {% endif %}
        </div>
    </section>
</main>
{% endblock %}


<script>
    document.addEventListener('DOMContentLoaded', function() {
        const likeButtons = document.querySelectorAll('.bxs-like');
        const dislikeButtons = document.querySelectorAll('.bxs-dislike');

        likeButtons.forEach(button => {
            button.addEventListener('click', () => {
                const likeCount = button.nextElementSibling;
                let count = parseInt(likeCount.textContent);
                if (button.classList.toggle('active')) {
                    likeCount.textContent = ++count;
                } else {
                    likeCount.textContent = --count;
                }
            });
        });

        dislikeButtons.forEach(button => {
            button.addEventListener('click', () => {
                const dislikeCount = button.nextElementSibling;
                let count = parseInt(dislikeCount.textContent);
                if (button.classList.toggle('active')) {
                    dislikeCount.textContent = ++count;
                } else {
                    dislikeCount.textContent = --count;
                }
            });
        });
    });
</script>

templates/generos.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Géneros
{% endblock %}
{% block main %}
<div class="container">
    <h1>Libros por Género</h1>
    {% for genero, libros in libros_por_genero.items %}
    <div class="genre-section">
        <h2>{{ genero }}</h2>
        <div class="carousel">
            <button class="carousel-button prev">&lt;</button>
            <div class="book-list">
                {% for libro in libros %}
                <div class="book-item">
                    <img src="{{ libro.cover_url }}" alt="{{ libro.title }}">
                </div>
                {% endfor %}
            </div>
            <button class="carousel-button next">&gt;</button>
        </div>
    </div>
    {% endfor %}
    
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Inicio
{% endblock %}

{% block main %}
<!-- Carrusel -->
<div class="carrusel">
    {% for libro in libros_random %}
    <div class="carrusel-item {% if forloop.first %}active{% endif %}">
        <div class="imagen-fondo">
            <img src="{% static 'images/background.jpg' %}" alt="Fondo">
        </div>
        <div class="contenido-libro">
            <div class="portada-libro">
                <img src="{{ libro.cover_url }}" alt="Portada del Libro">
            </div>
            <div class="descripcion-libro">
                <h3>{{ libro.title }}</h3>
                <p>{{ libro.first_sentence }}</p> <!-- Ajusta este campo según la descripción disponible -->
            </div>
        </div>
    </div>
    {% endfor %}
</div>

    <div class="carrusel-dots">
        <!-- Los puntos para navegación del carrusel -->
    </div> 

    <!-- Agrega esta sección al final de tu body --> 
    <div class="texto-encabezado">
        <h2>Explora Nuestros Libros</h2>
        <p>Descubre una amplia selección de libros recomendados para ti según tus intereses.</p>
    </div>    

    <section class="libros">
        <div class="fila-libros">
            {% if libros %}
                {% for libro in libros %}
                    <div class="libro">
                        <a href="{% url 'detalle_libro' libro.key|slice:'7:' %}">
                            <img src="{{ libro.cover_url }}" alt="{{ libro.title }}">
                        </a>
                        <p>{{ libro.title }}</p>
                    </div>
                {% endfor %}
            {% else %}
                <p>No se encontraron libros.</p>
            {% endif %}
        </div>
    </section>    
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
</head>

<body>
    <nav>
        <!-- Navegación similar a tu ejemplo -->
        <div class="nav-bar">
            <i class='bx bx-menu sidebarOpen'></i>
            <span class="logo navLogo"><a href="{% url 'index' %}">BookLand</a></span>
            <div class="menu">
                <div class="logo-toggle">
                    <span class="logo"><a href="{% url 'index' %}">BookLand</a></span>
                    <i class='bx bx-x siderbarClose'></i>
                </div>
                <ul class="nav-links">
                    <li><a href="{% url 'index' %}">Inicio</a></li>
                    <li><a href="{% url 'mis_libros' %}">Mis libros</a></li>
                    <li><a href="{% url 'geners' %}">Generos</a></li>
                    <li><a href="{% url 'writers' %}">Escritores</a></li>
                    <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                </ul>
            </div>
            <div class="darkLight-searchBox">
                <div class="dark-light">
                    <i class='bx bx-moon moon'></i>
                    <i class='bx bx-sun sun'></i>
                </div>
                <div class="searchBox">
                    <div class="searchToggle">
                        <i class='bx bx-x cancel'></i>
                        <i class='bx bx-search search'></i>
                    </div>
                    <div class="search-field">
                        <form method="GET" action="">
                            <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q|default:'' }}">
                            <i class='bx bx-search'></i>
                        </form>
                    </div>
                    <div class="logo-user">
                        <a href="{% url 'foto' %}">
                            <i class='bx bx-user-circle'></i>                            
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block main %}
    {% endblock %}
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/carrusel.js' %}"></script>
</body>

</html>

templates/mis_libros.html
{% extends "layout.html" %}
{% load static %}

{% block title %}
Mis Libros
{% endblock %}

{% block main %}

<main>
    <h2>Mis libros</h2>
    <section class="libros">
        <div class="fila-libros">
            {% for libro in liked_books %}
            <div class="libro">
                <a href="{% url 'detalle_libro' libro.olid %}">
                    <img src="{% if libro.cover %}{{ libro.cover }}{% else %}{% static 'img/no_cover.jpg' %}{% endif %}" alt="{{ libro.title }}">
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

templates/user.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styleuser.css' %}">
    <title>Perfil de Usuario</title>
    <style>
        .profile-picture-container {
            max-width: 100%;
            max-height: 200px;
            overflow: hidden;
        }

        .profile-picture-container img {
            width: 100%;
            height: auto;
        }

        /* Modal styles */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1000; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgba(0, 0, 0, 0.6); /* Black w/ opacity */
            justify-content: center;
            align-items: center;
            padding: 15px;
        }

        .modal-content {
            background-color: #fefefe00;
            margin: auto;
            padding: 30px;
            border: 1px solid #888;
            width: 100%;
            max-width: 500px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
            border-radius: 10px;
            animation: fadeIn 0.3s;
            position: relative;
        }

        .close {
            color: #aaa;
            position: absolute;
            right: 15px;
            top: 10px;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

        @keyframes fadeIn {
            from { opacity: 0; transform: scale(0.8); }
            to { opacity: 1; transform: scale(1); }
        }

        .modal h2 {
            margin-top: 0;
        }

        .modal label {
            display: block;
            margin-top: 10px;
            font-weight: bold;
        }

        .modal textarea,
        .modal input[type="file"] {
            width: 100%;
            margin-top: 5px;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #393737;
            font-size: 16px;
        }

        .modal button[type="submit"] {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }

        .modal button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .btn-index {
            display: inline-block;
            margin-bottom: 15px;
            padding: 10px 20px;
            background-color: #000000;
            color: white;
            text-align: center;
            border-radius: 5px;
            text-decoration: none;
            font-weight: 600;
        }

        .btn-index:hover {
            background-color: #535353;
        }
    </style>
</head>
<body>
    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center">
                <div class="col-xl-6 col-md-12">
                    <!-- Botón para ir al index -->
                    <a href="{% url 'index' %}" class="btn-index">Ir al Inicio</a>

                    <div class="card user-card-full">
                        <div class="row m-l-0 m-r-0">
                            <div class="col-sm-4 bg-c-lite-green user-profile">
                                <div class="card-block text-center text-white">
                                    <div class="m-b-25">
                                        {% if user.profile_picture %}
                                            <img src="{{ user.profile_picture.url }}" class="img-radius" alt="User Profile Image">
                                        {% else %}
                                            {% if user.gender == 'male' %}
                                                <img src="{% static 'images/user_male.webp' %}" class="img-radius" alt="Male Default Image">
                                            {% elif user.gender == 'female' %}
                                                <img src="{% static 'images/user_female.png' %}" class="img-radius" alt="Female Default Image">
                                            {% else %}
                                                <img src="{% static 'images/user_unknown.png' %}" class="img-radius" alt="Default User Image">
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                    <input type="text" class="f-w-600 text-center form-control" id="username" value="{{ user.username }}" readonly>
                                    <p>{{ user.biography }}</p>
                                    <a href="#" id="editBio" class="mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16">Editar biografía</a>
                                    <a href="#" id="editProfilePic" class="mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16">Cambiar foto de perfil</a>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="card-block">
                                    <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Información</h6>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Correo Electrónico</p>
                                            <h6 class="text-muted f-w-400">{{ user.email }}</h6>
                                        </div>
                                        <div class="col-sm-6">
                                            <p class="m-b-10 f-w-600">Contraseña</p>
                                            <h6 class="text-muted f-w-400">********</h6>
                                        </div>
                                    </div>
                                    <!-- user.html -->
                                    <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Preferencias</h6>
                                    <div class="row">
                                        <div class="card-block">
                                            <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Preferencias</h6>
                                            <form method="post" action="{% url 'foto' %}">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <label for="favorite_genres" class="m-b-10 f-w-600">Selecciona hasta 3 Géneros Favoritos de Lectura:</label>
                                                        <div id="generos-favoritos" class="btn-group" role="group" aria-label="Géneros de Lectura">
                                                            {% for genero in generos_populares %}
                                                                <button type="button" class="btn btn-outline-primary" data-genero="{{ genero }}">{{ genero }}</button>
                                                            {% endfor %}
                                                        </div>
                                                        <input type="hidden" name="favorite_genres" id="favorite_genres">
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-primary">Guardar Géneros Favoritos</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="editModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Editar Perfil</h2>
            <form method="post" action="{% url 'user_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="bioField">
                    <label for="id_biography">Nueva biografía:</label>
                    <textarea name="biography" id="id_biography">{{ user.biography }}</textarea>
                </div>
                <div id="profilePicField" style="display:none;">
                    <label for="id_profile_picture">Nueva foto de perfil:</label>
                    <input type="file" name="profile_picture" id="id_profile_picture">
                </div>
                <button type="submit">Guardar cambios</button>
            </form>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const editBioBtn = document.getElementById('editBio');
            const editProfilePicBtn = document.getElementById('editProfilePic');
            const modal = document.getElementById('editModal');
            const closeModal = document.querySelector('.modal .close');
            const bioField = document.getElementById('bioField');
            const profilePicField = document.getElementById('profilePicField');

            editBioBtn.addEventListener('click', function (e) {
                e.preventDefault();
                modal.style.display = 'flex';
                bioField.style.display = 'block';
                profilePicField.style.display = 'none';
            });

            editProfilePicBtn.addEventListener('click', function (e) {
                e.preventDefault();
                modal.style.display = 'flex';
                bioField.style.display = 'none';
                profilePicField.style.display = 'block';
            });

            closeModal.addEventListener('click', function () {
                modal.style.display = 'none';
            });

            window.addEventListener('click', function (event) {
                if (event.target == modal) {
                    modal.style.display = 'none';
                }
            });
        });

        document.addEventListener('DOMContentLoaded', () => {
            const buttons = document.querySelectorAll('#generos-favoritos button');
            buttons.forEach(button => {
                button.addEventListener('click', () => {
                    button.classList.toggle('btn-primary');
                    button.classList.toggle('btn-outline-primary');
                    updateSelectedGenres();
                });
            });

            function updateSelectedGenres() {
                const selectedGenres = Array.from(buttons)
                    .filter(button => button.classList.contains('btn-primary'))
                    .map(button => button.dataset.genero);
                document.getElementById('favorite_genres').value = selectedGenres.slice(0, 3).join(',');
            }
        });
    </script>
</body>
</html>